### ISSUE TITLE
"Unhandled exception. ByteDev.DotNet.Project.InvalidDotNetProjectException: Proje ct document contains no target framework." and "Unhandled exception. System.InvalidOperationException: Sequence contains more th an one matching element"

### ISSUE THREAD

**Issue by teroneko** [ByteDev/ByteDev.DotNet#2]
Please consider the fact, that a project can
1. using a non standard sdk, that does not require `<TargetFramework />` or `<TargetFrameworks />`
2. multi targeted, so it has `<TargetFrameworks />` and not `<TargetFramework />`
3. have both.
4. have a more than one `<TargetFramework />` or `<TargetFrameworks />`, you should take the latest.

And one more thought would be about `.props` and `.targets` imports. One thought would be, to load the intial XDocument, then look for Imports, and replace import by content of import at specific place of such import.

**Comment by teroneko** [comment]
By the way, there is a spelling misstake in your error message. :blush:

**Comment by teroneko** [comment]
Current workaround can be:
```
                    var projectDocument = XDocument.Load(projectFile);

                    var containsTargetFrameworkFramework = projectDocument.Root
                        .Elements("PropertyGroup")
                        .Elements("TargetFramework")
                        .Any();

                    if (!containsTargetFrameworkFramework) {
                        var targetTrameworkElement = new XElement("PropertyGroup",
                            new XElement("TargetFramework", ""));

                        projectDocument.Root.Add(targetTrameworkElement);
                    }
```

**Comment by ByteDev** [comment]
Are you sure `<TargetFrameworks />` is valid?

I think its supposed to always be `<TargetFramework>` but then ";" delimited values for multi target... if you have seen otherwise please let me know. Thanks

**Comment by ByteDev** [comment]
> 
> 
> By the way, there is a spelling misstake in your error message. 😊

Huh, wheres the spellling mistake? :-)

**Comment by teroneko** [comment]
You are writing a msbuild project parser and when you are parsing for, let's say TargetFramework, do you not want to know its possible existence and its possible non-existence? You have to adapt the rules a project file have. Asking for `Are you sure <TargetFrameworks /> is valid?` is not that great as programmer. You have to research such possible behaviour. Here the [reference](https://docs.microsoft.com/de-de/dotnet/standard/frameworks#how-to-specify-target-frameworks). The reason a TargetFramework or TargetFrameworks is required comes from the sdk Microsoft.NET.Sdk, but there are custom sdks's and those may not need such required properties like the sdk Microsoft.NET.Sdk does.

About your spelling misstake. I just copied the printed error. See title.

**Comment by ByteDev** [comment]
Now checks for TargetFrameworks and TargetFramework. No longer throws exception on neither.
Version 6.0.0 now on nuget.
